"""init

Revision ID: 1863ac1cb9d2
Revises: 7972a6cf0c0e
Create Date: 2024-06-10 16:36:40.330340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1863ac1cb9d2'
down_revision: Union[str, None] = '7972a6cf0c0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_details', sa.Column('expired_time', sa.DateTime(), nullable=True))
    op.add_column('otp_details', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'otp_details', 'users', ['email'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'otp_details', type_='foreignkey')
    op.drop_column('otp_details', 'is_active')
    op.drop_column('otp_details', 'expired_time')
    # ### end Alembic commands ###
