"""add email in payment system

Revision ID: 575d48fb13d0
Revises: 3806ffa7954f
Create Date: 2024-06-21 16:13:07.890342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '575d48fb13d0'
down_revision: Union[str, None] = '3806ffa7954f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('email', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'email')
    # ### end Alembic commands ###
