"""event managament system  detail

Revision ID: 83489c2601d0
Revises: a0b0eac39fad
Create Date: 2024-06-16 12:44:17.049557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83489c2601d0'
down_revision: Union[str, None] = 'a0b0eac39fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manager', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('manager', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('manager', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('manager', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manager', 'modified_at')
    op.drop_column('manager', 'created_at')
    op.drop_column('manager', 'is_active')
    op.drop_column('manager', 'is_deleted')
    # ### end Alembic commands ###
