"""event managament system  detail

Revision ID: bc0264a34168
Revises: 83489c2601d0
Create Date: 2024-06-16 15:44:59.993308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0264a34168'
down_revision: Union[str, None] = '83489c2601d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('E_manager_id', sa.String(length=50), nullable=True))
    op.drop_constraint('event_Event_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'manager', ['E_manager_id'], ['id'])
    op.drop_column('event', 'Event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('Event_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_Event_id_fkey', 'event', 'manager', ['Event_id'], ['id'])
    op.drop_column('event', 'E_manager_id')
    # ### end Alembic commands ###
