"""init

Revision ID: d3741f64a636
Revises: 1863ac1cb9d2
Create Date: 2024-06-10 16:41:04.604205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3741f64a636'
down_revision: Union[str, None] = '1863ac1cb9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('otp_details_email_fkey', 'otp_details', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('otp_details_email_fkey', 'otp_details', 'users', ['email'], ['id'])
    # ### end Alembic commands ###
