"""init

Revision ID: ecb388b62de7
Revises: 19e97d48420e
Create Date: 2024-06-11 10:06:55.643037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecb388b62de7'
down_revision: Union[str, None] = '19e97d48420e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_details', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('otp_details', sa.Column('expiry_time', sa.DateTime(), nullable=False))
    op.drop_column('otp_details', 'modified_at')
    op.drop_column('otp_details', 'is_active')
    op.drop_column('otp_details', 'expired_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_details', sa.Column('expired_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('otp_details', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('otp_details', sa.Column('modified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('otp_details', 'expiry_time')
    op.drop_column('otp_details', 'is_verified')
    # ### end Alembic commands ###
