"""init

Revision ID: f3882a81b801
Revises: 4a1b8571343c
Create Date: 2024-06-11 15:12:23.735685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3882a81b801'
down_revision: Union[str, None] = '4a1b8571343c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_details', 'is_verified')
    op.add_column('users', sa.Column('uname', sa.String(length=50), nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'uname')
    op.add_column('otp_details', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
